# ========================================================================================================================================
#
# Конфигурация плагина ECheck (Плагин на проверки для сервера EvatablePvP).
# Авторы плагина: iEatMeat, dobr_bobr2.
# GitHub: https://github.com/EvatablePvP/ECheck.
# Баг-трекер и предложения: https://github.com/EvatablePvP/ECheck/issues.
#
# Цвета в сообщениях поддерживаются в 'Legacy-Ampersand' формате (через символ '&';
# например, красный цвет - '&4'), больше информации тут: https://wiki.vg/Chat#Control_Sequences.
#
# HEX-цвета в сообщениях поддерживаются в 'Spigot' формате. (начиная с '&x' и с символами '&'
# как разделитель; например, цвет '#FF0000' - '&x&f&f&0&0&0&0').
# Мы рекомендуем использовать сервис https://rgb.birdflop.com/, где "Output Format" установлен на "Legacy".
#
# Аргументы используют Formatter из Java: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html.
# Если Вы используете аргументы по очереди, то можете использовать их как '%s' (например, даны аргументы '"hello", "world"';
# используя форматтер '%s %s!', Вы получите сообщение 'hello world!').
# Если Вы используете аргументы не по очереди, то можете использовать их число, например 1 аргумент становится `%1$s`
# (например, даны аргументы '"hello", "world"'; используя форматтер '%1$s %2$s, %1$s...', Вы получите сообщение 'hello world, hello...').
#
# ========================================================================================================================================

# Команды, выполняемые при бане.
# Аргументы: проверяемый, проверяющий, комментарий проверяющего.
command:
  ban: "ban %s Вы были забанены на проверке. Проверяющий: %s. Комментарий проверяющего: %s."
  admire: "ban %s Вы были забанены на проверке за признание. Проверяющий: %s. Комментарий проверяющего: %s."
  timeout: "ban %s Вы были забанены на проверке за игноирование проверки. Проверяющий: %s."
  quit: "ban %s Вы были забанены на проверке за выход из игры. Проверяющий: %s."
# Общее время проверки в секундах.
time: 600
# Период отправки напоминаний в чат, в секундах.
notifyTime: 10
# Запрещать плагинам отключать игрока от сервера во время проверки?
# Может быть полезно, если у Вас стоит античит, который может кикнуть игрока во время проверки.
# Этот не работает 100%, он ПЫТАЕТСЯ отменить отключения игрока от сервера.
preventKick: false
# Перемещать ли игрока в режим наблюдателя на время проверки?
# Может быть полезно, чтобы запретить "трапки на проверке" или разрешить игроку открывать чат на проверке.
spectator: false
# Капсулировать ли игрока на время проверки?
# Капсуляция перемещает игрока в центр блока, ставит под ним блок, очищает установленные внутри игрока блоки и защищает эти 3 блока (установленный блок и два блока воздуха над ним) от изменений.
# По окончании проверки этот блок и очищенные блоки будут возвращены в исходное состояние.
# Может быть полезно, чтобы запретить "трапки на проверке" или разрешить игроку открывать чат на проверке.
encapsulate: true
# Блок, установленный под игроком во время капсуляции.
# Список блоков: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
encapsulateMaterial: GLASS
# Надписи по центру экрана (тайтлы), отображаемые проверяемому при проверке.
# Аргументы: проверяющий, время (только для 'call').
title:
  # Надписи до остановки таймера.
  call:
    # Надписи.
    title: "&bПроверка!"
    subtitle: "&bВызвал: &c%1$s&b!"
    actionbar: "&bВремя: &c%2$s секунд&b!"
    # Время появления в тиках, отображения и исчезания для title и subtitle.
    fadeIn: 5
    stay: 10
    fadeOut: 5
    # Время повтора надписи в секундах.
    repeat: 1
  # Надписи после остановки таймера.
  wait:
    # Надписи.
    title: "&bПроверка!"
    subtitle: "&bВызвал: &c%1$s&b!"
    actionbar: "&bТаймер остановлен!"
    # Время появления в тиках, отображения и исчезания для title и subtitle.
    fadeIn: 5
    stay: 10
    fadeOut: 5
    # Время повтора надписи в секундах.
    repeat: 1
  # Надписи после отпуска проверяемого.
  release:
    # Надписи.
    title: "&bПроверка пройдена!"
    subtitle: "&c%1$s&b отпустил вас!"
    actionbar: "&bВы отпущены!"
    # Время появления в тиках, отображения и исчезания для title и subtitle.
    fadeIn: 5
    stay: 10
    fadeOut: 5
message:
  # Сообщение напоминания о проверке.
  reminder: |
    &bВы вызваны на проверку модератором &c%s&b!
    &bСкачайте &cDiscord &bс &cdiscord.com &bи отправьте свой ID в чат!
    &bУ Вас осталось &c%s&b секунд!
  # Сообщение, когда проверяемый вышел с сервера. Аргументы: проверяемый.
  left: "&bИгрок &c%s &bвышел с сервера!"
  # Сообщение, когда проверяющий вышел с сервера. Аргументы: проверяющий.
  leftPlayer: "&bВаш проверяющий, &c%s &bвышел с сервера! Вы отпущены с проверки!"
  # Сообщение, когда проверяемый не уложился во время. Аргументы: проверяемый.
  timeout: "&bИгрок &c%s не уложился во время проверки!"
  # Формат общения между проверяемым и проверяющим на проверке. Аргументы: отправитель, получатель, сообщение.
  chat: "&c%s &b>> &c%s&b: &7%s"
  # Сообщения для команды /check.
  command:
    # Сообщение при предоставлении неверного аргумента.
    invalid: "&4Неверный аргумент! &bИспользуйте &c/check help &bдля помощи!"
    # Сообщение, если исполнитель команды - не игрок.
    player: "&4Вы не игрок!"
    # Сообщение для /check help.
    help: |
      &bПомощь: &c/check help
      &bВызвать на проверку: &c/check call (игрок)
      &bОстановить таймер: &c/check stoptimer
      &bОтпустить с проверки: &c/check release
      &bЗабанить на проверке: &c/check ban [комментарий...]
      &bЗабанить за признание: &c/check admire [комментарий...]
    # Сообщения для /check call.
    call:
      # Сообщение для неверного кол-ва аргументов.
      usage: "&4Использование: &c/check call (игрок)"
      # Сообщение, если игрока с таким ником нет в сети.
      offline: "&4Игрок оффлайн!"
      # Сообщение, если модератор вызывает сам себя на проверку.
      self: "&4Вы не можете вызвать самого себя на проверку!"
      # Сообщение, если игрок защищен от проверок через право 'echeck.exempt'. Аргументы: проверяемый.
      exempt: "&4Игрок &c%s &4защищен от проверок!"
      # Сообщение, если проверяющий уже кого-то проверяет. Аргументы: проверяемый.
      alreadyYou: "&4Вы уже проверяете игрока &c%s&4!"
      # Сообщение, если проверяемый уже проверяется кем-то. Аргументы: проверяемый, проверяющий.
      alreadyPlayer: "&4Игрок &c%s &4уже проверяется модератором &c%s&4!"
      # Сообщение успешного выполнения команды. Аргументы: проверяемый.
      success: "&bВы вызвали игрока &c%s &bна проверку!"
      # Сообщение успешного выполнения команды для проверяемого. Аргументы: проверяющий.
      successPlayer: "&bМодератор &c%s &bвызвал Вас на проверку!"
    # Сообщения для /check stoptimer.
    stoptimer:
      # Сообщение, если исполнитель команды никого не проверяет.
      notChecking: "&4Вы не можете остановить таймер, так как Вы никого не проверяете!"
      # Сообщение, если таймер уже остановлен. Аргументы: проверяемый.
      already: "&4Вы уже остановили таймер игроку &c%s&4!"
      # Сообщение успешного выполнения команды. Аргументы: проверяемый.
      success: "&bВы остановили таймер игрока &c%s&b!"
      # Сообщение успешного выполнения команды для проверяемого. Аргументы: проверяющий.
      successPlayer: "&bМодератор &c%s &bостановил Ваш таймер проверки!"
    # Сообщения для /check release.
    release:
      # Сообщение, если исполнитель команды никого не проверяет.
      notChecking: "&4Вам некого отпускать с проверки!"
      # Сообщение успешного выполнения команды. Аргументы: проверяемый.
      success: "&bВы отпустили игрока &c%s &bс проверки!"
      # Сообщение успешного выполнения команды для проверяемого. Аргументы: проверяющий.
      successPlayer: "&bМодератор &c%s &bотпустил Вас с проверки!"
    # Сообщения для /check ban.
    ban:
      # Сообщение, если исполнитель команды никого не проверяет.
      notChecking: "&4Вам некого банить на проверке!"
      # Сообщение успешного выполнения команды. Аргументы: проверяемый, комментарий.
      success: "&bВы забанили игрока &c%s &bна проверке с комментарием &c%s&b!"
    # Сообщения для /check admire.
    admire:
      # Сообщение, если исполнитель команды никого не проверяет.
      notChecking: "&4Вам некого банить за признание на проверке!"
      # Сообщение успешного выполнения команды. Аргументы: проверяемый, комментарий.
      success: "&bВы забанили игрока &c%s &bна проверке за признание с комментарием &c%s&b!"
