name: ECheck
version: 0.1.2-SNAPSHOT
website: "https://github.com/EvatablePvP/ECheck"
description: "Плагин на проверки для сервера EvatablePvP"
authors: [iEatMeat, dobr_bobr2]
main: ru.evatablepvp.echeck.Main
api-version: 1.13
commands:
  echeck:
    usage: "/echeck [reload]"
    description: "Управляет плагином ECheck"
  check:
    usage: "/check (call (игрок)/stoptimer/release/ban [комментарий...]/admire [комментарий...])"
    description: "Управление проверками"
    permission: echeck.check
    aliases: freeze
